name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get latest go version
        id: version
        run: |
          echo ::set-output name=go_version::1.19.9
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.version.outputs.go_version }}
      - name: Build geosite
        id: build
        env:
          NO_SKIP: true
        run: |
          go run -v .
      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: geosite.db
          path: geosite.db
