name: Release
on:
  workflow_dispatch:
  schedule:
    - cron: "30 22 * * *"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get latest go version
        id: version
        run: |
          echo ::set-output name=go_version::1.19.9
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ steps.version.outputs.go_version }}
      - name: Build geosite
        id: build
        run: |
          go run -v .
      - name: Generate sha256 hash
        if: steps.build.outputs.skip != 'true'
        run: |
          mkdir dist
          cp geosite.db dist/
          sha256sum geosite.db > dist/geosite.db.sha256sum
      - name: Push artifacts to release branch
        if: steps.build.outputs.skip != 'true'
        run: |
          git config --local user.email "13503950+simplerick-simplefun@users.noreply.github.com"
          git config --local user.name "github-action[bot]"
          git fetch
          git checkout release
          git checkout --orphan release-orphan
          git rm -rf .
          
          cp dist/* .
          git add geosite.db
          git add geosite.db.sha256sum
          
          git commit -am "Updated at $(date)"
          git branch -D release
          git branch -m release
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: release
          force: true

      - name: Purge CDN Cache
        run: |
          curl -L https://purge.jsdelivr.net/gh/simplerick-simplefun/sing-geosite@release/geosite.db > /dev/null 2>&1
          curl -L https://purge.jsdelivr.net/gh/simplerick-simplefun/sing-geosite@release/geosite.db.sha256sum > /dev/null 2>&1

      - name: Release
        if: steps.build.outputs.skip != 'true'
        id: release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
          append_body: false
          fail_on_unmatched_files: true
          name: "${{ steps.build.outputs.tag }}"
          tag_name: "${{ steps.build.outputs.tag }}"
          files: |
            geosite.db
            geosite.db.sha256sum
